export enum ValidateProfileErrors {
   INCORRECT_USER_FIRST_NAME = 'INCORRECT_USER_FIRST_NAME',
   INCORRECT_USER_LAST_NAME = 'INCORRECT_USER_LAST_NAME',
   INCORRECT_USER_USER_NAME = 'INCORRECT_USER_USER_NAME',
   INCORRECT_AGE = 'INCORRECT_AGE',
   INCORRECT_CITY = 'INCORRECT_CITY',
   NO_DATA = 'NO_DATA',
   SERVER_ERROR = 'SERVER_ERROR',
}
