export const USER_LOCALSTORAGE_KEY = 'user'
export const THEME_LOCALSTORAGE_KEY = 'theme'
export const VIEW_LOCALSTORAGE_KEY = 'view'
export const LANGUAGE_LOCALSTORAGE_KEY = 'language'
export const ARTICLE_LIST_ITEM_INDEX = 'article_list_item_index'
